package main

import (
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"html/template"
	"log"
	"os"
	"path/filepath"
	"strings"
)

const annotation = "httpgen: "

var mode *string

func generate(pkg string, action string, appCtx string, inputType string, outputType string) string {
	var buff strings.Builder
	err := baseOutputFileTemplate.Execute(&buff, baseOutputFileTemplateData{
		Pkg:  pkg,
		Mode: *mode,
	})
	if err != nil {
		panic(err)
	}
	if *mode == "http" {
		err = httpHandlerTemplate.Execute(&buff, httpHandlerTemplateData{
			Action: action,
			Input:  inputType,
			Output: outputType,
			Ctx:    appCtx,
		})
		if err != nil {
			panic(err)
		}
	} else if *mode == "echo" {
		err = echoHandlerTemplate.Execute(&buff, httpHandlerTemplateData{
			Action: action,
			Input:  inputType,
			Output: outputType,
			Ctx:    appCtx,
		})
		if err != nil {
			panic(err)
		}
	}

	return buff.String()
}

type action struct {
	name   string
	input  string
	output string
}

func main() {

	mode = flag.String("mode", "http", "which http server you want to generate handler for [http, echo]")
	flag.Parse()
	if len(flag.Args()) < 1 {
		log.Fatalln("needs a filename")
	}
	filename := flag.Args()[0]

	inputFilePath, err := filepath.Abs(filename)
	if err != nil {
		panic(err)
	}
	pathList := filepath.SplitList(inputFilePath)
	pathList = pathList[:len(pathList)-1]
	dir := filepath.Join(pathList...)
	fset := token.NewFileSet()
	fast, err := parser.ParseFile(fset, filename, nil, parser.ParseComments)

	if err != nil {
		panic(err)
	}
	actualName := strings.TrimSuffix(filename, filepath.Ext(filename))
	outputFilePath := filepath.Join(dir, fmt.Sprintf("%s_httpgen_gen.go", actualName))
	outputFile, err := os.Create(outputFilePath)
	if err != nil {
		panic(err)
	}
	defer outputFile.Close()

	var ctx string
	var actions map[string]*action = make(map[string]*action)
	pkg := fast.Name.String()

	for _, decl := range fast.Decls {
		if _, ok := decl.(*ast.GenDecl); ok {
			declComment := decl.(*ast.GenDecl).Doc.Text()
			if len(declComment) > 0 && declComment[:len(annotation)] == annotation {
				name := decl.(*ast.GenDecl).Specs[0].(*ast.TypeSpec).Name.String()
				arguments := strings.Split(strings.Trim(declComment[len(annotation):], " \n\t\r"), " ")
				typ := arguments[0]
				if typ == "ctx" {
					ctx = name
				} else if typ == "input" {
					actionName := arguments[1]
					if _, exists := actions[actionName]; !exists {
						actions[actionName] = &action{
							name:  actionName,
							input: name,
						}
					}

					actions[actionName].input = name
				} else if typ == "output" {
					actionName := arguments[1]
					if _, exists := actions[actionName]; !exists {
						actions[actionName] = &action{
							name:   actionName,
							output: name,
						}
					}

					actions[actionName].output = name
				} else {
					log.Fatalf("type %s not supported\n", typ)
				}
			}
		}
	}

	for _, action := range actions {
		fmt.Fprint(outputFile, generate(pkg, action.name, ctx, action.input, action.output))
	}

	fmt.Printf("%+v\n", actions["UserCreate"])
}

var (
	baseOutputFileTemplate = template.Must(template.New("httpgen-base").Parse(baseOutputFile))
	httpHandlerTemplate    = template.Must(template.New("httpgen-http").Parse(httpHandler))
	echoHandlerTemplate    = template.Must(template.New("httpgen-echo").Parse(echoHandler))
)

type baseOutputFileTemplateData struct {
	Pkg  string
	Mode string
}

type httpHandlerTemplateData struct {
	Action string
	Input  string
	Output string
	Ctx    string
}

const httpHandler = `
func Make{{.Action}}Handler(appCtx *{{ .Ctx }}, h func(*{{ .Ctx }}, {{.Input}}) ({{.Output}}, error)) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var input {{.Input}}
		err := json.NewDecoder(r.Body).Decode(&input)
		if err != nil {
			panic(err)
		}
		resp, err := h(appCtx, input)
		if err != nil {
			panic(err)
		}


		err = json.NewEncoder(w).Encode(resp)
		if err != nil {
			panic(err)
		}
	}
}
`
const echoHandler = `
func Make{{.Action}}Handler(appCtx *{{ .Ctx }}, h func(*{{ .Ctx }}, {{.Input}}) ({{.Output}}, error)) echo.HandlerFunc {
	return func(c echo.Context) error {
		var input {{.Input}}
		err := json.NewDecoder(c.Request().Body).Decode(&input)
		defer c.Request().Body.Close()
		if err != nil {
			panic(err)
		}
		resp, err := h(appCtx, input)
		if err != nil {
			c.Error(err)
		}
		return c.JSON(200, resp)
	}
}
`
const baseOutputFile = `// Code generated by go-toolbox
// Source code: https://github.com/amirrezaask/go-toolbox
package {{ .Pkg }}

import (
	{{ if eq .Mode "http" }}
    "net/http"
	{{ end }}
	"encoding/json"

	{{ if eq .Mode "echo" }}
	"github.com/labstack/echo/v4"
	{{ end }}
)
`
