package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"html/template"
	"log"
	"os"
	"path/filepath"
	"strings"
)

const annotation = "httpgen: "

func generate(pkg string, typeName string, fields map[string]string, tags []string, args map[string]string) string {
	var buff strings.Builder
	err := baseOutputFileTemplate.Execute(&buff, baseOutputFileTemplateData{
		Pkg: pkg,
	})
	if err != nil {
		panic(err)
	}
	return buff.String()
}

func main() {
	if len(os.Args) < 2 {
		log.Fatalln("needs a filename")
	}
	filename := os.Args[1]

	inputFilePath, err := filepath.Abs(filename)
	if err != nil {
		panic(err)
	}
	pathList := filepath.SplitList(inputFilePath)
	pathList = pathList[:len(pathList)-1]
	dir := filepath.Join(pathList...)
	fset := token.NewFileSet()
	fast, err := parser.ParseFile(fset, filename, nil, parser.ParseComments)

	if err != nil {
		panic(err)
	}
	actualName := strings.TrimSuffix(filename, filepath.Ext(filename))
	outputFilePath := filepath.Join(dir, fmt.Sprintf("%s_httpgen_gen.go", actualName))
	outputFile, err := os.Create(outputFilePath)
	if err != nil {
		panic(err)
	}
	defer outputFile.Close()
	for _, decl := range fast.Decls {
		if _, ok := decl.(*ast.GenDecl); ok {
			declComment := decl.(*ast.GenDecl).Doc.Text()
			if len(declComment) > 0 && declComment[:len(annotation)] == annotation {
				name := decl.(*ast.GenDecl).Specs[0].(*ast.TypeSpec).Name.String()
				// arguments := strings.Split(strings.Trim(declComment[len(annotation)+1:], " \n\t\r"), " ")
				fields := make(map[string]string)
				for _, field := range decl.(*ast.GenDecl).Specs[0].(*ast.TypeSpec).Type.(*ast.StructType).Fields.List {
					for _, name := range field.Names {
						fields[name.String()] = fmt.Sprint(field.Type)
					}
				}
				args := make(map[string]string)
				// for _, argkv := range arguments {
				// 	splitted := strings.Split(argkv, "=")
				// 	args[splitted[0]] = splitted[1]
				// }
				output := generate(fast.Name.String(), name, fields, nil, args)
				fmt.Fprint(outputFile, output)
			}
		}
	}

}

var (
	baseOutputFileTemplate = template.Must(template.New("sqlgen-base").Parse(baseOutputFile))
)

type baseOutputFileTemplateData struct {
	Pkg string
}

type httpHandlerTemplateData struct {
	Action string
	Input  string
	Output string
}

const httpHandler = `
func Make{{.Action}}Handler(h func({{.Input}}) ({{.Output}}, error)) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var input {{.Input}}
		err := json.NewDecoder(r.Body).Decode(&input)
		if err != nil {
			panic(err)
		}
		resp, err := h(input)
		if err != nil {
			panic(err)
		}


		err = json.NewEncoder(w).Encode(resp)
		if err != nil {
			panic(err)
		}
	}
}
`

const baseOutputFile = `
// Code generated by Crafting-Table.
// Source code: https://github.com/snapp-incubator/crafting-table
package {{ .Pkg }}

import (
    "fmt"
    "strings"
    "http"
)
`
