package main

import (
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"html/template"
	"log"
	"os"
	"path/filepath"
	"strings"
)

const annotation = "handler"

var mode *string

func generate(pkg string, action string, appCtx string, inputType string, outputType string, handler string) string {
	var buff strings.Builder
	err := baseOutputFileTemplate.Execute(&buff, baseOutputFileTemplateData{
		Pkg:  pkg,
		Mode: *mode,
	})
	if err != nil {
		panic(err)
	}
	if *mode == "http" {
		err = httpHandlerTemplate.Execute(&buff, httpHandlerTemplateData{
			Action: action,
			Input:  inputType,
			Output: outputType,
			Ctx:    appCtx,
			Handler: handler,
		})
		if err != nil {
			panic(err)
		}
	} else if *mode == "echo" {
		err = echoHandlerTemplate.Execute(&buff, httpHandlerTemplateData{
			Action: action,
			Input:  inputType,
			Output: outputType,
			Ctx:    appCtx,
			Handler: handler,
		})
		if err != nil {
			panic(err)
		}
	}

	return buff.String()
}

type action struct {
	name   string
	input  string
	output string
	handler string
}

func main() {

	mode = flag.String("mode", "http", "which http server you want to generate handler for [http, echo]")
	flag.Parse()
	if len(flag.Args()) < 1 {
		log.Fatalln("needs a filename")
	}
	filename := flag.Args()[0]

	inputFilePath, err := filepath.Abs(filename)
	if err != nil {
		panic(err)
	}
	pathList := filepath.SplitList(inputFilePath)
	pathList = pathList[:len(pathList)-1]
	dir := filepath.Join(pathList...)
	fset := token.NewFileSet()
	fast, err := parser.ParseFile(fset, filename, nil, parser.ParseComments)

	if err != nil {
		panic(err)
	}
	actualName := strings.TrimSuffix(filename, filepath.Ext(filename))
	outputFilePath := filepath.Join(dir, fmt.Sprintf("%s_httpgen_gen.go", actualName))
	outputFile, err := os.Create(outputFilePath)
	if err != nil {
		panic(err)
	}
	defer outputFile.Close()

	pkg := fast.Name.String()
	for _, decl := range fast.Decls {
		_, isFnDecl := decl.(*ast.FuncDecl)
		if isFnDecl {
			declComment := decl.(*ast.FuncDecl).Doc.Text()
			if len(declComment) > 0 && declComment[:len(annotation)] == annotation {
				fnDecl := decl.(*ast.FuncDecl)
				handlerName := decl.(*ast.FuncDecl).Name.String()
				appCtxTypeName := fnDecl.Type.Params.List[0].Type.(*ast.StarExpr).X.(*ast.Ident).Name
				requestTypeName :=  fnDecl.Type.Params.List[1].Type.(*ast.Ident).Name
				responseTypeName :=  fnDecl.Type.Results.List[0].Type.(*ast.Ident).Name
				fmt.Fprint(outputFile, generate(pkg, handlerName, appCtxTypeName, requestTypeName, responseTypeName, handlerName))
			
		}
	}
		
	}
}

var (
	baseOutputFileTemplate = template.Must(template.New("httpgen-base").Parse(baseOutputFile))
	httpHandlerTemplate    = template.Must(template.New("httpgen-http").Parse(httpHandler))
	echoHandlerTemplate    = template.Must(template.New("httpgen-echo").Parse(echoHandler))
)

type baseOutputFileTemplateData struct {
	Pkg  string
	Mode string
}

type httpHandlerTemplateData struct {
	Action string
	Input  string
	Output string
	Ctx    string
	Handler string
}

const httpHandler = `
func {{.Action}}Handler(appCtx *{{ .Ctx }}) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var input {{.Input}}
		err := json.NewDecoder(r.Body).Decode(&input)
		if err != nil {
			panic(err)
		}
		resp, err := {{ .Handler }}(appCtx, input)
		if err != nil {
			panic(err)
		}


		err = json.NewEncoder(w).Encode(resp)
		if err != nil {
			panic(err)
		}
	}
}
`
const echoHandler = `
func {{.Action}}Handler(appCtx *{{ .Ctx }}) echo.HandlerFunc {
	return func(c echo.Context) error {
		var input {{.Input}}
		err := json.NewDecoder(c.Request().Body).Decode(&input)
		defer c.Request().Body.Close()
		if err != nil {
			panic(err)
		}
		resp, err := {{ .Handler }}(appCtx, input)
		if err != nil {
			c.Error(err)
		}
		return c.JSON(200, resp)
	}
}
`
const baseOutputFile = `// Code generated by httpgen; DO NOT EDIT.
// Source code: https://github.com/amirrezaask/go-toolbox/cmd/httpgen
package {{ .Pkg }}

import (
	{{ if eq .Mode "http" }}
    "net/http"
	{{ end }}
	"encoding/json"

	{{ if eq .Mode "echo" }}
	"github.com/labstack/echo/v4"
	{{ end }}
)
`
