// enum generates safe, fast enumerationfor your.
//
// Usage:
//
//	enumgen $GOFILE
//
// enum program parses your source code and looks for "enum: variants..." pattern
// in your decl comments at top level of your file, when found if it's a type declaration
// it will generate enum code for you.

package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/iancoleman/strcase"
)

const usage = `usage:
	enum <input file that contains enum decorators> 
`

const (
	ENUM_PREFIX    = "__ENUM__"
	ENUM_DECORATOR = "enumgen"
)

const enumTemplate = `
// Code generated by go-toolbox
// Source code: https://github.com/amirrezaask/go-toolbox
package {{ .Pkg }}
import "fmt"
type {{ .TypeName }} struct {
	variant int
}
var (
	{{ range $index, $variant := .Variants }}
	{{ $.EnumName }}{{ $variant }} = {{ $.TypeName }} { {{ $index }} }
	{{ end }}
)
func {{ .EnumName }}FromString(s string) ({{ .TypeName }}, error) {
	switch s {
		{{ range $index, $variant  := .Variants }}
	case "{{.}}":
		return {{$.TypeName}}{ {{$index}} }, nil
	{{ end }}
	default:
		return {{.TypeName}}{}, fmt.Errorf("invalid {{.EnumName}} variant: %s", s)
	}
}
func (e {{.TypeName}}) String() string {
	switch e.variant {
		{{ range $index, $variant := .Variants }}
	case {{$index}}:
		return "{{$variant}}"
	{{ end }}
	default:
		return ""
	} 
}
`

func genEnumStruct(pkg string, name string, variants []string) string {
	codename := fmt.Sprintf("%s%s", ENUM_PREFIX, name)

	type enumStruct struct {
		Pkg      string
		TypeName string
		EnumName string
		Variants []string
	}
	t := template.Must(template.New("enum").Parse(enumTemplate))
	var buff strings.Builder
	err := t.Execute(&buff, enumStruct{
		Pkg:      pkg,
		EnumName: strcase.ToCamel(name),
		TypeName: codename,
		Variants: variants,
	})
	if err != nil {
		panic(err)
	}
	return buff.String()
}

func main() {
	if len(os.Args) < 2 {
		fmt.Print(usage)
		fmt.Println("")
		return
	}
	filename := os.Args[1]

	inputFilePath, err := filepath.Abs(filename)
	if err != nil {
		panic(err)
	}
	pathList := filepath.SplitList(inputFilePath)
	pathList = pathList[:len(pathList)-1]
	dir := filepath.Join(pathList...)
	fset := token.NewFileSet()
	fast, err := parser.ParseFile(fset, filename, nil, parser.ParseComments)

	if err != nil {
		panic(err)
	}
	actualName := strings.TrimSuffix(filename, filepath.Ext(filename))
	outputFilePath := filepath.Join(dir, fmt.Sprintf("%s_enumgen_gen.go", actualName))
	outputFile, err := os.Create(outputFilePath)
	if err != nil {
		panic(err)
	}
	defer outputFile.Close()
	for _, decl := range fast.Decls {
		if _, ok := decl.(*ast.GenDecl); ok {
			declComment := decl.(*ast.GenDecl).Doc.Text()
			if len(declComment) > 0 && declComment[:len(ENUM_DECORATOR)] == ENUM_DECORATOR {
				name := decl.(*ast.GenDecl).Specs[0].(*ast.TypeSpec).Name.String()
				variants := strings.Split(strings.Trim(declComment[len(ENUM_DECORATOR)+1:], " \n\t\r"), " ")
				enum := genEnumStruct(fast.Name.String(), name, variants)
				_, err := fmt.Fprint(outputFile, enum)
				if err != nil {
					panic(err)
				}
			}
		}

	}

}
